const mongoose = require("mongoose");

// Sub-schema for detailed nutritional data
const nutritionSchema = new mongoose.Schema({
  calories: { type: Number, default: 0 },
  protein: { type: Number, default: 0 }, 
  carbs: { type: Number, default: 0 },   
  fat: { type: Number, default: 0 },     
  fiber: { type: Number, default: 0 },    
  servingSize: { type: Number },
  servingUnit: { type: String }
}, { _id: false });

// Sub-schema for the items generated by the AI
const aiFoodItemSchema = new mongoose.Schema({
  parsed_food_name: { 
    type: String, 
    required: true 
  },
  quantity: { 
    type: Number, 
    required: true, 
    default: 1 
  },
  unit: { 
    type: String, 
    default: "serving" 
  },
  description: { 
    type: String 
  },
  confidence: { 
    type: Number 
  },
  nutrition: nutritionSchema, 
  source: { 
    type: String, 
    default: "api" 
  }
}, { _id: true });

const aiMealSchema = new mongoose.Schema({
  email: {
    type: String,
    required: true,
    lowercase: true,
    trim: true
  },
  original_description: {
    type: String,
    required: true
  },
  mealType: {
    type: String,
    enum: ["breakfast", "lunch", "dinner", "snack"],
    required: true
  },
  date: {
    type: Date,
    default: Date.now
  },
  items: [aiFoodItemSchema],
  total_calories: {
    type: Number,
    default: 0
  }
}, { timestamps: true });

// Calculate total calories before saving
aiMealSchema.pre("save", async function() {
  this.total_calories = this.items.reduce((sum, item) => {
    return sum + (item.nutrition?.calories || 0);
  }, 0);
  // No next() needed – returning a promise tells Mongoose to proceed
});

module.exports = mongoose.model("AIMeal", aiMealSchema);