const mongoose = require("mongoose");

const foodItemSchema = new mongoose.Schema({
  "Food_Item": { type: String, required: true },
  "Category": String,
  "Calories (kcal)": Number,
  "Protein (g)": Number,
  "Carbohydrates (g)": Number,
  "Fat (g)": Number,
  "Fiber (g)": Number,
  "Sugars (g)": Number,
  "Sodium (mg)": Number,
  "Cholesterol (mg)": Number,
  "Meal_Type": String,
  "Water_Intake (ml)": Number,
  "Weight_per_Unit_g": Number,
  "fiber_g": Number,
  "sugar_g": Number,
  "calcium_mg": Number,
  "iron_mg": Number,
  "magnesium_mg": Number,
  "phosphorus_mg": Number,
  "potassium_mg": Number,
  "sodium_mg_detailed": Number,
  "zinc_mg": Number,
  "vitamin_a_mcg": Number,
  "vitamin_b1_mg": Number,
  "vitamin_b2_mg": Number,
  "vitamin_b3_mg": Number,
  "vitamin_b6_mg": Number,
  "vitamin_b12_mcg": Number,
  "vitamin_c_mg": Number,
  "vitamin_d_mcg": Number,
  "vitamin_e_mg": Number,
  "vitamin_k_mcg": Number,
  "folate_mcg": Number,
  "saturated_fat_g": Number,
  "monounsaturated_fat_g": Number,
  "polyunsaturated_fat_g": Number,
  "trans_fat_g": Number,
  "cholesterol_mg_detailed": Number,
  "omega_3_g": Number,
  "omega_6_g": Number,
  "isAIUpgraded": { type: Boolean, default: false }
});

module.exports = mongoose.model("FoodItem", foodItemSchema);